title: blacklabnz
position: Data Engineer
description: Former DevOps Engineer
email: 
keywords: DevOps Data
github_link: https://github.com/blacklabnz
linkedin: https://www.linkedin.com/in/neilxu
avatar: ./assets/img/avatar.png
google_analytics: G-FDV12HCDKK
favicon: ./assets/img/favicon-cloud.png
favicon_dark: ./assets/img/favicon-cloud.png
canonical: https://unknownyet/
