title: blacklabnz
position: Data Engineer
description: Data Engineer DevOps Engineer
prev_position: Former DevOps Engineer
email: 
keywords: DevOps Data
social:
  name: Neil Xu
  links:
    - https://www.linkedin.com/in/neilxu
    - https://github.com/blacklabnz
avatar: ./assets/img/avatar.png
google_analytics: G-FDV12HCDKK
favicon: 
  light: ./assets/img/favicon-cloud.png
  dark: ./assets/img/favicon-cloud.png
canonical: https://blacklabnz.github.io
url: https://blacklabnz.github.io
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
